[build-system]
requires = [
    "cmake>=3.18",
    "setuptools>=42",
    "wheel",
    "packaging",
    "shiboken6==6.4.2",
    "PySide6==6.4.2",
    "shiboken6_generator==6.4.2",
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel.linux]
build-verbosity = 1