[build-system]
requires = [
    "cmake>=3.18",
    "setuptools>=42",
    "wheel",
    "shiboken6",
    "PySide6",
    "shiboken6_generator",
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel.linux]
before-build = "cibuildwheel/before_build.sh"
build-verbosity = 1